### ISSUE TITLE
Asami corrections

### ISSUE THREAD

**Issue by quoll** [clojurelog/clojurelog.github.io#5]
On the document "[Open Source Clojure-Datalog Databases](https://clojurelog.github.io/)" a couple of things are incorrect for Asami:

**Ad-hoc "document" storage (i.e. maps of arbitrary types)**: Can be "Planned" ([Issue](https://github.com/threatgrid/asami/issues/103)) _(working on this right now)_
**`byte-array` value type**: Yes
**Composite Tuples**: Still Planned, now with ([Issue](https://github.com/threatgrid/asami/issues/168))  _(they're now supported internally, but the API doesn't let them through yet)_
**Graal Native Image**: Yes
**CLI console**: Yes _(though it's a bit primitive. It creates graphs and loads files into them, and it answers queries)_

**Comment by deobald** [comment]
@quoll I believe I got everything, but please do have a quick double-check over the page. Thanks for raising these.
