### ISSUE TITLE
Does crux belong here as well?

### ISSUE THREAD

**Issue by SSYH** [clojurelog/clojurelog.github.io#8]

**Comment by refset** [comment]
Hi @SSYH perhaps we should have clarified with "XTDB (formerly Crux)" - sorry for the confusion! But yeah...we re-named it :) see https://twitter.com/xtdb_com/status/1435593730921218058

**Comment by deobald** [comment]
We can remove this in a couple months, but I've mentioned the rename to avoid future confusion:

https://github.com/clojurelog/clojurelog.github.io/commit/874e9b2634febf401d46078e8352061a3280516f
